{% set version = "0.4.0" %}

package:
    name: opensim-moco
    version: {{ version }}

source:
    git_url: https://github.com/opensim-org/opensim-moco.git
    git_rev: conda
    folder: opensim-moco-source

build:
    number: 2
    skip: true # [win and vc<14]
    detect_binary_files_with_prefix: true
    run_exports:
        - {{ pin_subpackage('opensim-moco', min_pin='x.x', max_pin='x') }}

requirements:
    build:
        - git
        - cmake
        - ninja  # [win]
        - autoconf  # [unix]
        - libtool  # [unix]
        - automake  # [unix]
        - pkg-config  # [unix]
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - swig 3.0.12
        - freeglut  # [linux]
        - ipopt  # [unix]
        # - simbody >=3.7
        - python
        - numpy x.x
    host:
        # TODO simbody uses openblas
        - libblas
        - liblapack
        - freeglut  # [linux]
        - ipopt  # [unix]
        # - simbody >=3.7
        - python
        - numpy x.x
    run:
        - python
        - numpy x.x
        - freeglut  # [linux]
        - ipopt  # [unix]
        # - simbody >=3.7

about:
    home: https://opensim.stanford.edu/moco
    license: Apache 2.0
    license_file: LICENSE.txt
    summary: Musculoskeletal optimal control
    dev_url: https://github.com/opensim-org/opensim-moco

extra:
    recipe_maintainers:
        - chrisdembia

# Run with conda-build --channel conda-forge . 
# This avoids using Anaconda's Intel Math Kernel Library.
#
