name: Windows

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  conda:
    name: conda-build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
  
# https://github.com/reactos/reactos/pull/2688/files
#     - name: Add Visual C++ to PATH 
#       uses: ilammy/msvc-dev-cmd@v1
#       with:
#         # Visual C++ associated with Visual Studio 2017 version 15.9
#         # https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering
#         toolset: 14.16

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: packaging
        python-version: 3.7
        
    - name: Initialize Conda for Powershell
      shell: pwsh
      run: conda install --channel conda-forge conda-build anaconda-client conda-verify

    - name: Deploy Conda package
      shell: cmd
      run: |
        echo "activate"
        conda activate packaging
        echo "config"
        conda config --set anaconda_upload yes
        echo "login"
        anaconda login --hostname github-actions-windows-%random% --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
        echo "build"
        conda-build --channel conda-forge --user opensim-org .
        echo "logout"
        anaconda logout
