name: Windows

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  conda:
    name: conda-build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
  
    - uses: goanpeca/setup-miniconda@v1.0.1
      with:
        auto-update-conda: true
        activate-environment: packaging
        python-version: 3.7
        
    - name: Initialize Conda for Powershell
      shell: pwsh
      run: conda install --channel conda-forge anaconda-client conda-verify

    - name: Deploy Conda package
      run: |
        echo "activate"
        conda activate packaging
        echo "config"
        # conda config --set anaconda_upload yes
        echo "login"
        # anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
        echo "build"
        # conda-build --channel conda-forge --user opensim-org .
        # conda-build --channel conda-forge --user opensim-org --token ${{ secrets.ANACONDA_TOKEN }} .
        conda-build --channel conda-forge .
        echo "logout"
        anaconda logout
